### ISSUE TITLE
posting links

### ISSUE THREAD

**Issue by dnoesgaard** [JBGruber/atrrr#26]
Is this behavior expected

```
> atrrr::post_skeet("New paper https://specimenpub.org/collection/collection_5/")
Error in magick::image_read(image) : pecimenpub.org/collection/collection_5/
  path must be URL, filename or raw vector
✖ Something went wrong [311ms]  
```
Is is not possible to share links?

**Comment by JBGruber** [comment]
Intersting edge case. The preview endpoint (https://cardyb.bsky.app/v1/extract) delivers an image link in this case, but an empty (i.e. `""`). Hence the error. I added an exception and it works not in the development version. Thanks for reporting!

**Comment by dnoesgaard** [comment]
Ah so this was specific to the URL I was trying to include?

**Comment by JBGruber** [comment]
I've never seen the enpoint behave like this. Usually the `image` field simply does not exist if there is no preview image. But I doubt it's a unique issue, so good to have it covered!
